version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  convert-dz1:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: echo 'export PATH=/home/circleci/.local/lib/python3.8/site-packages:$PATH' >> $BASH_ENV
      - run:
          name: Jupyter get HTML
          command: |
            jupyter nbconvert —execute —to html dz1.ipynb
            
      - store_artifacts:
          path: ./dz1.html

workflows:
  main:
    jobs:
      - convert-dz1