version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  convert-dz1:
    executor: python/default
    steps:
      - run:
          name: Jupyter get HTML
          command: |
            cd teaching_practice
            pip install -r ./requirements.txt
            jupyter nbconvert —execute —to html dz1.ipynb
            
      - store_artifacts:
          path: ./dz1.html

workflows:
  main:
    jobs:
      - convert-dz1