version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  kagglification:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: dependencies
      - python/install-deps
      - save_cache:
          key: dependencies
          paths:
            - "venv"
      - run: echo 'export PATH=/home/circleci/.local/lib/python3.8/site-packages:$PATH' >> $BASH_ENV
      - run:
          name: Kaggle get data
          command: |
            kaggle competitions download titanic
      - run:
          name: Execute notebook
          command: |
            jupyter nbconvert --to notebook --inplace --execute nmtp.ipynb
      - store_artifacts:
          path: ./titanic-predictions.csv
      - run:
          name: Kaggle submit data
          command: |
            kaggle competitions submit titanic -f ./titanic-predictions.csv -m "Titanic Submission"

workflows:
  main:
    jobs:
      - kagglification
      
      