version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  convert-dz1:
    executor: python/default
    steps:
      - store_artifacts:
          path: /dz1.html
          destination: artifact-file

workflows:
  main:
    jobs:
      - convert-dz1